version: '3.8'
services:
  db:
    container_name: movie-portal-db
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    env_file: ./.env.docker
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
